[context.deploy-preview]
  title = "SMI - Service Mesh Interface (Preview)"

[build]
publish = "public"
command = "hugo -t smi"

[context.production.environment]
HUGO_VERSION = "0.40.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.40.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.40.3"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.40.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
